package rakutenapi

type AutoGenerated struct {
	GenreInformation []any `json:"GenreInformation"`
	Items            []struct {
		Item Item `json:"Item"`
	} `json:"Items"`
	TagInformation []any `json:"TagInformation"`
	Carrier        int   `json:"carrier"`
	Count          int   `json:"count"`
	First          int   `json:"first"`
	Hits           int   `json:"hits"`
	Last           int   `json:"last"`
	Page           int   `json:"page"`
	PageCount      int   `json:"pageCount"`
}
type Item struct {
	AffiliateRate      int     `json:"affiliateRate"`
	AffiliateURL       string  `json:"affiliateUrl"`
	AsurakuArea        string  `json:"asurakuArea"`
	AsurakuClosingTime string  `json:"asurakuClosingTime"`
	AsurakuFlag        int     `json:"asurakuFlag"`
	Availability       int     `json:"availability"`
	Catchcopy          string  `json:"catchcopy"`
	CreditCardFlag     int     `json:"creditCardFlag"`
	EndTime            string  `json:"endTime"`
	GenreID            string  `json:"genreId"`
	GiftFlag           int     `json:"giftFlag"`
	ImageFlag          int     `json:"imageFlag"`
	ItemCaption        string  `json:"itemCaption"`
	ItemCode           string  `json:"itemCode"`
	ItemName           string  `json:"itemName"`
	ItemPrice          int     `json:"itemPrice"`
	ItemPriceBaseField string  `json:"itemPriceBaseField"`
	ItemPriceMax1      int     `json:"itemPriceMax1"`
	ItemPriceMax2      int     `json:"itemPriceMax2"`
	ItemPriceMax3      int     `json:"itemPriceMax3"`
	ItemPriceMin1      int     `json:"itemPriceMin1"`
	ItemPriceMin2      int     `json:"itemPriceMin2"`
	ItemPriceMin3      int     `json:"itemPriceMin3"`
	ItemURL            string  `json:"itemUrl"`
	MediumImageUrls    []Image `json:"mediumImageUrls"`
	PointRate          int     `json:"pointRate"`
	PointRateEndTime   string  `json:"pointRateEndTime"`
	PointRateStartTime string  `json:"pointRateStartTime"`
	PostageFlag        int     `json:"postageFlag"`
	ReviewAverage      float64 `json:"reviewAverage"`
	ReviewCount        int     `json:"reviewCount"`
	ShipOverseasArea   string  `json:"shipOverseasArea"`
	ShipOverseasFlag   int     `json:"shipOverseasFlag"`
	ShopAffiliateURL   string  `json:"shopAffiliateUrl"`
	ShopCode           string  `json:"shopCode"`
	ShopName           string  `json:"shopName"`
	ShopOfTheYearFlag  int     `json:"shopOfTheYearFlag"`
	ShopURL            string  `json:"shopUrl"`
	SmallImageUrls     []Image `json:"smallImageUrls"`
	StartTime          string  `json:"startTime"`
	TagIds             []int   `json:"tagIds"`
	TaxFlag            int     `json:"taxFlag"`
}
type Image struct {
	ImageURL string `json:"imageUrl"`
}
